
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or fallback to the values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xceitaturyhtqzuoibrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZWl0YXR1cnlodHF6dW9pYnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzUxMjcsImV4cCI6MjA2MDE1MTEyN30.s3-c1JLi2M1GwN1IrF9kTB841ZSkpOgs7pFTYm7K7K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
